spring.application.name=SB-DMS-SERVICE
server.port=2222


spring.datasource.url=jdbc:mysql://localhost:3306/c
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

dms.save.successInsert="SUCCESS : Department Details Inserted"
dms.db.fail="FAILED : DB Error"
#ems.save.fail="FAILED : Invalid Employee details"
dms.save.successUpdate="SUCCESS : Department Details Updated"
dms.delete.successDelete="SUCCESS : Department Details Deleted"
dms.invalid.emp-notfound="FAILED : Department Details Not Found"
dms.invalid.emp-details="FAILED : Invalid Department details"


eureka.instance.hostname=localhost

#Stop registering as a client. It is a Server
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true