spring.application.name=SB-PMS
server.port=1234

#database connection properties 
# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/c
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

pms.save.successInsert="SUCCESS : Product Details Saved"
pms.db.fail="FAIL : Product Details Not Saved"
pms.save.successUpdate="SUCCESS : Product Details Updated"
pms.delete.successDelete="SUCCESS : Product Details Deleted"
pms.find.successFound="SUCCESS : Product Details Found"
pms.invalid.pms-details="FAILED : Invalid Product details"
pms.invalid.pms-notfound="FAILED : Product Details Not Found"