spring.application.name=SB-SMS-SERVICE
server.port=4444


eureka.instance.hostname=localhost
spring.datasource.url=jdbc:mysql://localhost:3306/c
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

sms.save.successInsert="SUCCESS : Supplier Details Saved"
sms.db.fail="FAIL : Supplier Details Not Saved"
sms.save.successUpdate="SUCCESS : Supplier Details Updated"
sms.delete.successDelete="SUCCESS : Supplier Details Deleted"
sms.find.successFound="SUCCESS : Supplier Details Found"
sms.invalid.sup-details="FAILED : Invalid Supplier details"
sms.invalid.sup-notfound="FAILED : Product Supplier Not Found"
#Stop registering as a client. It is a Server

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true